
import React from 'react';
import { useStore } from '../store/useStore';
import { SEO } from '../components/SEO';
import { FileText, ShieldCheck, Download } from 'lucide-react';

export const UserLicenseAgreement: React.FC = () => {
  const { isDarkMode } = useStore();

  return (
    <div className="pb-32">
      <SEO title="User License Agreement" description="Pinegroove Synchronization License Agreement. Terms and conditions for music usage." />
      
      {/* Hero Header - Simplified with brand gradient instead of image */}
      <div className={`relative h-[40vh] min-h-[300px] flex items-center justify-center overflow-hidden transition-colors duration-500 ${isDarkMode ? 'bg-zinc-950' : 'bg-sky-50'}`}>
        <div className={`absolute inset-0 z-0 opacity-20 dark:opacity-40 bg-gradient-to-br from-sky-500 via-indigo-600 to-purple-700`}></div>

        <div className="relative z-10 text-center px-4 max-w-4xl mx-auto">
          <FileText size={48} className={`mx-auto mb-6 ${isDarkMode ? 'text-sky-400' : 'text-sky-600'}`} />
          <h1 className={`text-4xl md:text-6xl font-black mb-4 tracking-tight uppercase ${isDarkMode ? 'text-white' : 'text-zinc-900'}`}>
            User License Agreement
          </h1>
          <p className={`text-xl font-medium tracking-wide ${isDarkMode ? 'text-zinc-400' : 'text-zinc-600'}`}>
            Terms and Conditions for Music Synchronization
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="container mx-auto px-6 relative z-20 -mt-16 md:-mt-20">
        <div className={`max-w-4xl mx-auto rounded-3xl shadow-2xl border overflow-hidden ${isDarkMode ? 'bg-zinc-900 border-zinc-800 text-zinc-300' : 'bg-white border-zinc-100 text-zinc-700'}`}>
          
          {/* Header Image inside the card - Changed to h-auto to prevent logo cropping */}
          <div className="w-full bg-zinc-100 dark:bg-zinc-800 overflow-hidden">
            <img 
              src="https://pub-704d512baed74c069032320c83ebe2f7.r2.dev/youtube-template-gumroad-new.webp" 
              alt="User License Agreement Header" 
              className="w-full h-auto block"
            />
          </div>

          <div className="p-8 md:p-14 prose prose-lg dark:prose-invert max-w-none space-y-12">
            
            {/* Section: Parties */}
            <section>
              <h2 className="text-2xl font-black mb-6 text-sky-500 border-b pb-2 border-sky-500/20">Parties</h2>
              <div className="space-y-4 leading-relaxed">
                <p>
                  This User License Agreement (“Agreement”) is entered into between <strong>Francesco Biondi</strong>, composer and producer (“Licensor”), and you, the purchaser of the license (“Licensee”).
                </p>
                <p>
                  Licensor is the sole and exclusive owner (100%) of all rights in and to the musical composition(s) and the corresponding master recording(s), including copyright and neighboring rights.
                  <br />
                  <span className="text-sm opacity-70 italic">(Except for public domain works rearranged and re-recorded by Licensor, for which Licensor owns 100% of the arrangement and master.)</span>
                </p>
                <p>By purchasing a license, Licensee agrees to be bound by the terms set forth herein.</p>
              </div>
            </section>

            {/* Section: License Certificate */}
            <section>
              <h2 className="text-2xl font-black mb-6 text-sky-500 border-b pb-2 border-sky-500/20">License Certificate</h2>
              <div className="space-y-4">
                <p>Upon purchase, Licensee receives a downloadable License Certificate, automatically generated by the Licensor’s website. The License Certificate includes:</p>
                <ul className="grid md:grid-cols-2 gap-x-8 gap-y-2 list-none p-0">
                  <li className="flex items-center gap-2"><div className="w-1.5 h-1.5 bg-sky-500 rounded-full" /> Licensee name</li>
                  <li className="flex items-center gap-2"><div className="w-1.5 h-1.5 bg-sky-500 rounded-full" /> Transaction ID and purchase date</li>
                  <li className="flex items-center gap-2"><div className="w-1.5 h-1.5 bg-sky-500 rounded-full" /> Title of the licensed musical work</li>
                  <li className="flex items-center gap-2"><div className="w-1.5 h-1.5 bg-sky-500 rounded-full" /> ISWC (where applicable)</li>
                  <li className="flex items-center gap-2"><div className="w-1.5 h-1.5 bg-sky-500 rounded-full" /> Type of license purchased (Standard or Extended)</li>
                </ul>
                <div className={`mt-6 p-6 rounded-2xl flex flex-col md:flex-row items-center justify-between gap-4 ${isDarkMode ? 'bg-zinc-800/50' : 'bg-sky-50'}`}>
                  <p className="text-sm m-0">The License Certificate serves as formal proof of the granted synchronization license.</p>
                  <a href="https://www.pinegroove.net/my-purchases" className="flex items-center gap-2 bg-sky-600 hover:bg-sky-500 text-white font-bold py-2.5 px-6 rounded-full text-sm transition-all shadow-md shrink-0">
                    <Download size={16} /> My Purchases
                  </a>
                </div>
              </div>
            </section>

            {/* Section: License Grant */}
            <section>
              <h2 className="text-2xl font-black mb-6 text-sky-500 border-b pb-2 border-sky-500/20">License Grant</h2>
              <div className="space-y-4">
                <p>Licensor grants Licensee a non-exclusive, perpetual, worldwide synchronization license to use the musical work(s) in accordance with the license type purchased (Standard or Extended).</p>
                <p>This license permits synchronization of the music with visual, audiovisual, or spoken-word content in a single or multiple end products depending on the license type.</p>
              </div>
            </section>

            {/* Section: Standard License */}
            <section className={`p-8 rounded-3xl border ${isDarkMode ? 'bg-zinc-950/40 border-zinc-800' : 'bg-slate-50 border-slate-200'}`}>
              <h2 className="text-2xl font-black mb-6 flex items-center gap-3">
                <ShieldCheck className="text-emerald-500" /> Standard License – Permitted Uses
              </h2>
              <p className="mb-6 opacity-80">The Standard License allows the music to be used for:</p>
              <ul className="grid md:grid-cols-2 gap-4 list-none p-0 text-sm md:text-base">
                {[
                  "Web-based content (websites, landing pages)",
                  "Social media content (YouTube, IG, FB, TikTok)",
                  "Podcasts and audio-only online shows",
                  "Personal projects and client projects",
                  "Educational projects and school assignments",
                  "Charity and non-profit films",
                  "Tutorials, explainers, and online courses",
                  "Monetization of ONE (1) social media channel"
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <div className="mt-1 w-4 h-4 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0">
                      <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full" />
                    </div>
                    {item}
                  </li>
                ))}
              </ul>
              <div className="mt-8 pt-6 border-t border-dashed border-zinc-300 dark:border-zinc-700">
                <p className="text-xs font-bold uppercase tracking-widest opacity-60 m-0">Note</p>
                <p className="m-0 text-sm italic opacity-80">Audience size and number of views are not limited for the permitted platforms.</p>
              </div>
            </section>

            {/* Section: Extended License */}
            <section className={`p-8 rounded-3xl border ${isDarkMode ? 'bg-sky-950/10 border-sky-900/30' : 'bg-sky-50 border-sky-100'}`}>
              <h2 className="text-2xl font-black mb-6 flex items-center gap-3">
                <ShieldCheck className="text-sky-500" /> Extended License – Permitted Uses
              </h2>
              <p className="mb-6 opacity-80">The Extended License includes all uses permitted under the Standard License, plus:</p>
              <ul className="grid md:grid-cols-2 gap-4 list-none p-0 text-sm md:text-base">
                {[
                  "Television and radio productions",
                  "Films (short, feature, documentaries)",
                  "OTT / VOD platforms and streaming services",
                  "Advertising and commercial campaigns",
                  "Video games and interactive media",
                  "Mobile and desktop applications",
                  "Industrial, corporate, and institutional use",
                  "Trade fairs, exhibitions, installations",
                  "Unlimited DVD / Blu-ray distribution",
                  "Monetization of multiple channels"
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <div className="mt-1 w-4 h-4 rounded-full bg-sky-500/20 flex items-center justify-center shrink-0">
                      <div className="w-1.5 h-1.5 bg-sky-500 rounded-full" />
                    </div>
                    {item}
                  </li>
                ))}
              </ul>
              <div className="mt-8 pt-6 border-t border-dashed border-sky-300/30">
                <p className="text-xs font-bold uppercase tracking-widest opacity-60 m-0">Note</p>
                <p className="m-0 text-sm italic opacity-80">Distribution territory, number of copies, broadcasts, streams, and audience size are unlimited.</p>
              </div>
            </section>

            {/* Section: Restrictions */}
            <section>
              <h2 className="text-2xl font-black mb-6 text-red-500 border-b pb-2 border-red-500/20">Restrictions</h2>
              <p className="mb-6 font-bold">Licensee may NOT:</p>
              <ul className="space-y-4 list-none p-0">
                {[
                  { key: 'A', text: 'Sell, sublicense, resell, share, trade, or give away the music as a stand-alone product' },
                  { key: 'B', text: 'Create covers, remixes, adaptations, or derivative musical works' },
                  { key: 'C', text: 'Include the music in music-only products, albums, or compilations' },
                  { key: 'D', text: 'Register the music in any Content ID or automated copyright enforcement system' },
                  { key: 'E', text: 'Redistribute the music as part of templates or stock products for multiple end users' },
                  { key: 'F', text: 'Use the music for ringtones or similar telecommunication uses' },
                  { key: 'G', text: 'AI Training / Machine Learning: Licensee may not use the licensed music to train, fine-tune, or improve artificial intelligence or machine learning models. This includes, but is not limited to, using the music as part of datasets, input data, or reference material for generating new AI-based content, music, or audio models.' }
                ].map((item) => (
                  <li key={item.key} className="flex gap-4">
                    <span className="font-black text-red-500 bg-red-500/10 w-8 h-8 rounded-lg flex items-center justify-center shrink-0">{item.key}</span>
                    <span className="opacity-90">{item.text}</span>
                  </li>
                ))}
              </ul>
            </section>

            {/* Section: Cue Sheet */}
            <section className={`p-8 rounded-3xl ${isDarkMode ? 'bg-zinc-800/30' : 'bg-zinc-50'}`}>
              <h2 className="text-2xl font-black mb-6 text-sky-500 border-b pb-2 border-sky-500/20">Cue Sheet & Performing Rights</h2>
              <p className="mb-6">Where required, cue sheets must credit:</p>
              <div className="grid sm:grid-cols-2 gap-6 bg-white dark:bg-black/20 p-6 rounded-2xl border dark:border-zinc-800">
                <div className="space-y-1">
                  <p className="text-xs uppercase font-bold opacity-50 m-0">Composer</p>
                  <p className="font-bold m-0 text-lg">Francesco Biondi</p>
                </div>
                <div className="space-y-1">
                  <p className="text-xs uppercase font-bold opacity-50 m-0">P.R.O.</p>
                  <p className="font-bold m-0 text-lg">BMI</p>
                </div>
                <div className="space-y-1">
                  <p className="text-xs uppercase font-bold opacity-50 m-0">IPI Number</p>
                  <p className="font-mono font-bold m-0 text-lg">00542050494</p>
                </div>
              </div>
              <p className="mt-6 text-sm italic opacity-70">
                ISWC codes are shown in the track details column of the corresponding track pages or in your License Certificate.
              </p>
            </section>

            {/* Section: Indemnification */}
            <section>
              <h2 className="text-2xl font-black mb-6 text-sky-500 border-b pb-2 border-sky-500/20">Indemnification</h2>
              <p className="leading-relaxed">
                Licensee agrees to indemnify, defend, and hold Licensor harmless from any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys’ fees) arising from any breach of this Agreement.
              </p>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
};
